version: '3'

services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    environment:
      - SECRET_KEY
