version: '3'

services:
  app:
    build: .
    command: python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    environment:
      - SECRET_KEY
