version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver_plus --cert-file ./server-cert.pem --key-file ./server-key.pem"
    volumes:
      - .:/code
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    environment:
      - SECRET_KEY
