version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "python3 manage.py migrate; gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8000:8000"
    tty: true
    stdin_open: true
    environment:
      - SECRET_KEY
  nginx:
    #    restart: always
    image: nginx:1.15.12-alpine
    depends_on:
      - webapp
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./prodo/static:/var/www/ai-keiba/static/"
