version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "python3 manage.py migrate --noinput; python manage.py collectstatic --noinput --clear; gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8000:8000"
    tty: true
    stdin_open: true
    environment:
      - SECRET_KEY
  nginx:
    #    restart: always
    image: nginx:1.15.12-alpine
    depends_on:
      - app
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./prodo/static:/var/www/font/static/"
      - "/var/www/font/wellknown/:/var/www/font/wellknown/"
      - "/etc/letsencrypt/archive/piyopiyo.de/:/etc/letsencrypt/archive/piyopiyo.de/"
