# Generated by Django 4.1.4 on 2022-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmap',
            name='kanji',
            field=models.CharField(default='魚', max_length=1),
        ),
    ]
