# Generated by Django 4.1.4 on 2022-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_bitmap_kanji"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitmap",
            name="memo",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
